# Generated by Django 4.1.13 on 2024-03-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_students_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
