# Generated by Django 4.1.13 on 2024-03-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnmodel',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='learnmodel',
            name='folder_upload',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
